apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-netsocs-configurations
data:  
  DB_HOST: {{ .Values.mysql.host }}
  DB_USER: {{ .Values.mysql.user }}
  DB_PASS: {{ .Values.mysql.password }}
  DB_PORT: "{{ .Values.mysql.port }}"
  DB_NAME: {{ .Values.mysql.dbname }}
  
  MONGO_HOST: {{ .Release.Name }}-mongodb
  MONGO_PORT: "{{ .Values.mongodb.service.port }}"
  MONGO_USER: {{ .Values.mongodb.user }}
  MONGO_PASS: {{ .Values.mongodb.password }}
  MONGO_DATABASE: {{ .Values.mongodb.dbname }}
  # firstdeploy-redis-master
  REDIS_HOST: {{ .Values.redis.host }}
  REDIS_PASS: {{ .Values.redis.password }}

  # SHA VERSION
  ACCESS_CONTROL_IMAGE_TAG: "main"