services:
    db:
        image: mysql:8.0
        restart: always
        env_file:
            - .env
        ports:
            - "3306:3306"
        volumes:
            - my-db:/var/lib/mysql
    mongo:
        image: mongodb/mongodb-community-server:latest
        restart: always
        env_file:
            - .env
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db
    redis:
        image: redis:latest
        restart: always
        command: redis-server --requirepass ${REDIS_PASSWORD}
        env_file:
            - .env
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
    caddy:
        image: caddy:latest
        restart: always
        env_file:
            - .env
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        volumes:
            - ./conf:/etc/caddy
            - ./site:/srv
            - caddy_data:/data
            - caddy_config:/config
volumes:
    my-db:
        driver: local
    mongo-data:
        driver: local
    redis-data:
        driver: local
    caddy_data:
        driver: local
    caddy_config:
        driver: local
