apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: {{ .Values.registry }}/service.kc/main:main
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: 8443
          env:
            - name: KEYCLOAK_LOGLEVEL
              value: "ALL"
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin123"
            - name: KC_DB
              value: "mysql"
            - name: KC_DB_URL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-netsocs-configurations
                  key: DB_NAME
            - name: KC_PROXY
              value: "edge"
            - name: KC_HOSTNAME
              value: {{ .Values.httpHostname }}/auth
            - name: KC_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-netsocs-configurations
                  key: DB_USER
            - name: KC_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-netsocs-configurations
                  key: DB_PASS
            - name: KC_DB_URL_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-netsocs-configurations
                  key: DB_HOST
            - name: KC_DB_URL_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-netsocs-configurations
                  key: DB_PORT
      
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
spec:
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: insecure-skip-verify
  namespace: default
spec:
  serverName: keycloak-service
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak-ingressroute
  namespace: default
spec:
  routes:
    - match: Host(`{{ .Values.httpHostname | replace "https://" "" }}`) && PathPrefix(`/auth`)
      kind: Rule
      priority: 10
      middlewares:
        - name: sec-headers
      services:
        - name: keycloak-service
          port: 8443
          scheme: https
          serversTransport: insecure-skip-verify
