apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-traefik-configurator
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: {{ .Release.Name }}-traefik-configurator
      restartPolicy: OnFailure
      containers:
      - name: configurator
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Configurando Traefik de kube-system..."
          
          # Deshabilitar Traefik de kube-system
          echo "Deshabilitando Traefik de kube-system..."
          kubectl patch daemonset -n kube-system traefik-ingress-controller \
            -p '{"spec": {"template": {"spec": {"nodeSelector": {"non-existent-label": "true"}}}}}'
          
          # Esperar a que el pod termine
          echo "Esperando que el pod termine..."
          sleep 15
          
          # Configurar hostPorts en Traefik de default
          echo "Configurando hostPorts en Traefik de default..."
          kubectl patch deployment {{ .Release.Name }}-traefik --type='json' -p='[
            {"op": "add", "path": "/spec/template/spec/containers/0/ports/1/hostPort", "value": 8080},
            {"op": "add", "path": "/spec/template/spec/containers/0/ports/2/hostPort", "value": 80},
            {"op": "add", "path": "/spec/template/spec/containers/0/ports/3/hostPort", "value": 443}
          ]' || echo "hostPorts ya configurados"
          
          echo "Configuración completada."
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-traefik-configurator
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-traefik-configurator
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-traefik-configurator
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
