on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        type: string
      service_type:
        description: 'Type of service to release'
        required: true
        type: choice
        options:
        - /service.driver_hub/backend
        - /module.access_control/backend
        - /module.automation/backend
        - /module.configuration/backend_v2
        - /module.configuration/frontend
        - /module.dashboard/backendv2
        - /module.dashboard/frontend
        - /service.kc/main
      new_sha:
        description: 'New sha of the service'
        required: true
        type: string
      netsocs_version:
        description: 'Netsocs version'
        required: true
        type: string
jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Version: ${{ inputs.version }}"
          echo "Netsocs version: ${{ inputs.netsocs_version }}"
    
  set-app-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set app version
        run: |
          sed -i 's/^version: .*/version: ${{ inputs.version }}/' netsocs-helm-chart/Chart.yaml
          sed -i 's/^appVersion: .*/appVersion: ${{ inputs.version }}/' netsocs-helm-chart/Chart.yaml
          chmod +x update-sha.sh
          ./update-sha.sh ${{ inputs.service_type }} ${{ inputs.new_sha }}
          ./update-version.sh ${{ inputs.netsocs_version }}
      - uses: azure/setup-helm@v4.3.0
      - name: Package chart
        run: |
          helm package netsocs-helm-chart -d charts
          helm repo index .
      - name: Commit changes
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m "Update version to ${{ inputs.version }}"
          git push